# Wake Word Detection
wake_word:
  access_key: "YOUR_PICOVOICE_ACCESS_KEY_HERE"
  keyword: "hey-genio"  # Built-in keyword name (ignored if keyword_path is set)
  keyword_path: null  # Path to custom .ppn file (e.g., "models/wake_words/my_custom_word.ppn")
  sensitivity: 0.5  # Range: 0.0-1.0. Lower = fewer false positives but may miss wake word. Higher = more responsive but more false positives. Try 0.6-0.7 if experiencing responsiveness issues.

# Voice Activity Detection
vad:
  sample_rate: 16000
  frame_duration: 30  # milliseconds
  mode: 3  # 0=Quality, 1=Low Bitrate, 2=Aggressive, 3=Very Aggressive
  
# Speech to Text (using Vosk)
stt:
  # Path to the Vosk model directory
  # Download from: https://alphacephei.com/vosk/models
  # For Swedish: vosk-model-small-sv-rhasspy-0.15 (recommended for Pi 5)
  # or vosk-model-sv-se-0.22 (larger, more accurate)
  model_path: "models/vosk/vosk-model-small-sv-rhasspy-0.15"
  language: "sv"  # Swedish
  sample_rate: 16000  # Audio sample rate in Hz
  
  # Audio recording options for debugging
  save_recordings: false  # Set to true to save all audio recordings for debugging
  recordings_dir: "recordings"  # Directory where recordings will be saved
  
  # Post-processing corrections for common misrecognitions
  enable_corrections: true  # Enable/disable automatic text corrections
  custom_corrections: {}  # Add custom corrections like {"wrong phrase": "correct phrase"}
  
  # Legacy Faster-Whisper parameters below are kept for backward compatibility
  # but are not used by Vosk. You can safely ignore them.
  model: "base"  # Not used with Vosk
  device: "cpu"  # Not used with Vosk
  compute_type: "int8"  # Not used with Vosk
  beam_size: 8  # Not used with Vosk
  temperature: 0.0  # Not used with Vosk
  initial_prompt: "Detta är en konversation på svenska med vardagliga fraser och meningar."  # Not used with Vosk
  condition_on_previous_text: true  # Not used with Vosk
  vad_filter: true  # Not used with Vosk
  vad_min_silence_duration: 700  # Not used with Vosk

# MQTT / n8n Integration
mqtt:
  broker: "your-cluster.hivemq.cloud"
  port: 8883
  username: "your_mqtt_username"
  password: "your_mqtt_password"
  topic_send: "assistant/input"
  topic_receive: "assistant/output"
  use_tls: true
  keepalive: 60
  qos: 1

# Text to Speech
tts:
  model_path: "models/piper/sv_SE-lisa-medium.onnx"
  config_path: "models/piper/sv_SE-lisa-medium.onnx.json"
  speaker: 0

# Audio Settings
audio:
  input_device: null  # null = default device, or device index number
  output_device: null  # null = default device, or device index number
  sample_rate: 16000
  channels: 1
  chunk_size: 1024

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
